<?php
use PHPExcel;
require_once('./vendor/Classes/PHPExcel.php');
// Create new PHPExcel object
$objPHPExcel = new PHPExcel();
// Set document properties
$objPHPExcel->getProperties()->setCreator("Maarten Balliauw")
    ->setLastModifiedBy("Maarten Balliauw")
    ->setTitle("Office 2007 XLSX Test Document")
    ->setSubject("Office 2007 XLSX Test Document")
    ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
    ->setKeywords("office 2007 openxml php")
    ->setCategory("Test result file");

$repName = 'Sales Orders' ;
$columNumber = array('SaleOrderNumber'=>'Order #', 'SaleOrderDate'=>'Sale Date','VendorCustomerName'=>'Vendor Name','shipname'=>'Ship To','totalamount'=>'Total Amount','ShippingVendorName'=>'Ship Via',
    'ShippingVendorTrackingAPI'=>'Tracking #','Status'=>'Status','Transaction'=>'Transaction');

$columHeader = array('Order #', 'Sale Date','Vendor Name','Ship To','Total Amount','Ship Via','Tracking #','Status','Transaction');
//--- header
$numCols = count($columHeader);
$objPHPExcel->setActiveSheetIndex(0)
    ->setCellValueByColumnAndRow(0, 1, $repName)
    ->mergeCellsByColumnAndRow(0, 1, $numCols-1, 1);

$objPHPExcel->getActiveSheet()->getStyleByColumnAndRow(0, 1)->applyFromArray(
    array(
        "font" => array(
            "name" => "Times New Roman",
            "bold" => true,
            "italic" => false,
            "size" => 20
        ),
        "alignment" => array(
            "horizontal" => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            "vertical" => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            "wrap" => true
        )
    ));
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(50);

$objPHPExcel->getActiveSheet()->freezePaneByColumnAndRow(0, 3);

//Set col title
$objPHPExcel->getActiveSheet()->fromArray($columHeader,NULL,'A2');
$col = "H";
$objPHPExcel->getActiveSheet()->getStyle('E')->getNumberFormat()->setFormatCode('"$"#,##0.00_-');
foreach (range('A', $objPHPExcel->getActiveSheet()->getHighestDataColumn()) as $col) {
    $objPHPExcel->getActiveSheet()
        ->getColumnDimension($col)
        ->setAutoSize(true);
}
//--- write data

$result=$this->result;

if(!empty($result))
{
    $row = 3;$j=0;
    foreach($result as $record){
        $i = 0;
        $objPHPExcel->setActiveSheetIndex(0);
        foreach($columNumber as $key=>$val){
            if($key =='No'){
                $value = $j;
            }elseif($key =='SaleOrderDate'){
                $timestamp = strtotime($record[$key]);
                $SODate = date("m/d/Y", $timestamp);
                $value  = $SODate;
            } elseif($key=='totalamount'){
                $value  = number_format($record[$key],2,'.','');
            } elseif($key=='Transaction'){
                    if($record["Sale"]==1){
                    $value  = "Sale";
                    }elseif($record["Consignment"]==1){
                    $value  = "On consignment";
                    }elseif($record["POReturn"]==1){
                    $value  = "Return";
                    }else{
                    $value ="";
                }
            }
            else{
                $value  = $record[$key];
            }
            $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($i,$row,$value);
            $i++;
        }
        $row++; $j++;
    }
    $row=$row+1;
    for($i=1;$i<3;$i++){
        if($i==1){
            $value="Total Amount";
        }else{
            $value="$".number_format($this->overallTotal,2,'.','');
        }
        $objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($i,$row,$value);
    }
    $row=$row+1;
    for($i=1;$i<3;$i++){
        if($i==1){
            $value="Coins Count";
        }else{
            $value=$this->overallCount;
        }
        $objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($i,$row,$value);
    }
}
ob_end_clean();
//--------------------------------------------------------------

// Rename worksheet
$objPHPExcel->getActiveSheet()->setTitle($repName);

// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);
    //Second sheet
    // Create a new worksheet, after the default sheet
    $objPHPExcel->createSheet();

    // Add some data to the second sheet, resembling some different data types
    $objPHPExcel->setActiveSheetIndex(1);
    $objPHPExcel->getActiveSheet()->setCellValue('A1', 'More data');

    // Rename 2nd sheet
    $objPHPExcel->getActiveSheet()->setTitle('Second sheet');
//

$repName = str_replace(" ","_",$repName) ;

$fileName = "SaleOrder-" . date("Ymd") . ".xlsx";
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename=' . $fileName);
header('Cache-Control: max-age=0');
ob_end_clean();
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');

exit;

?>
